package uz.murodjon.robotcallv2.siptrunk.application.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import uz.murodjon.robotcallv2.agent.ami.AmiClient;
import uz.murodjon.robotcallv2.shared.util.SecretCipher;
import uz.murodjon.robotcallv2.siptrunk.application.port.output.SipTrunkRepository;
import uz.murodjon.robotcallv2.siptrunk.domain.entity.SipTrunk;
import uz.murodjon.robotcallv2.siptrunk.infrastructure.config.PjsipConfigProperties;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Renders PJSIP blocks for managed trunks into Asterisk config file.
 * Supports configurable audio codecs / HD voice (G.722, Opus, ULAW, ALAW) per trunk.
 */
@Service
public class PjsipConfigWriter {

    private static final Logger log = LoggerFactory.getLogger(PjsipConfigWriter.class);
    private static final String HEADER = """
            ; Generated by PjsipConfigWriter (report #7) — DO NOT EDIT BY HAND.
            ; Rewritten from scratch every time a managed sip_trunk row changes; any
            ; manual edit here is lost on the next trunk create/update/delete.
            ; #include this file from pjsip.conf's [global] section (or anywhere top-level).

            """;

    private final SipTrunkRepository repo;
    private final SecretCipher cipher;
    private final PjsipConfigProperties props;
    private final AmiClient ami;

    public PjsipConfigWriter(SipTrunkRepository repo, SecretCipher cipher, PjsipConfigProperties props,
                              AmiClient ami) {
        this.repo = repo;
        this.cipher = cipher;
        this.props = props;
        this.ami = ami;
    }

    public void regenerateAndReload() {
        if (!props.enabled()) {
            return;
        }
        if (props.configDir() == null || props.configDir().isBlank()) {
            log.warn("voice-agent.siptrunk.config-dir is not set — cannot write generated PJSIP config");
            return;
        }
        List<SipTrunk> trunks = repo.findAllManagedEnabled();
        Path file = Path.of(props.configDir(), props.configFileName());
        try {
            Files.writeString(file, render(trunks), StandardCharsets.UTF_8);
        } catch (IOException e) {
            log.warn("Could not write {}: {}", file, e.getMessage());
            return;
        }
        boolean reloaded = ami.reloadPjsip();
        log.info("Regenerated {} ({} managed trunk(s)) — Asterisk reload {}",
                file, trunks.size(), reloaded ? "ok" : "skipped/failed, will retry on next change");
    }

    private String render(List<SipTrunk> trunks) {
        StringBuilder sb = new StringBuilder(HEADER);
        for (SipTrunk trunk : trunks) {
            appendTrunk(sb, trunk);
        }
        return sb.toString();
    }

    private void appendTrunk(StringBuilder sb, SipTrunk trunk) {
        String password;
        try {
            password = cipher.decrypt(trunk.sipPasswordEnc());
        } catch (Exception e) {
            log.warn("Skipping trunk {} in generated PJSIP config — password could not be decrypted: {}",
                    trunk.id(), e.getMessage());
            return;
        }
        String endpoint = trunk.pjsipEndpoint();
        String authId = endpoint + "-auth";
        String aorId = endpoint + "-aor";
        String hostPort = trunk.host() + ":" + trunk.port();

        sb.append("; --- sip_trunk.id=").append(trunk.id())
                .append(" (company_id=").append(trunk.companyId()).append(") ---\n");

        sb.append('[').append(authId).append("]\n");
        sb.append("type = auth\n");
        sb.append("auth_type = userpass\n");
        sb.append("username = ").append(trunk.sipUsername()).append('\n');
        sb.append("password = ").append(password).append("\n\n");

        sb.append('[').append(endpoint).append("-reg]\n");
        sb.append("type = registration\n");
        sb.append("transport = transport-trunk\n");
        sb.append("outbound_auth = ").append(authId).append('\n');
        sb.append("server_uri = sip:").append(hostPort).append('\n');
        sb.append("client_uri = sip:").append(trunk.sipUsername()).append('@').append(hostPort).append('\n');
        sb.append("retry_interval = 60\n");
        sb.append("expiration = 120\n\n");

        sb.append('[').append(endpoint).append("]\n");
        sb.append("type = endpoint\n");
        sb.append("transport = transport-trunk\n");
        sb.append("context = from-trunk\n");
        sb.append("disallow = all\n");

        // Codecs: if configured per trunk (e.g. ["g722", "opus", "ulaw", "alaw"]), apply in order of preference
        List<String> codecs = (trunk.codecs() != null && !trunk.codecs().isEmpty()) ? trunk.codecs() : List.of("ulaw", "alaw");
        for (String codec : codecs) {
            if (codec != null) {
                String trimmed = codec.trim().toLowerCase();
                if (!trimmed.isEmpty()) {
                    sb.append("allow = ").append(trimmed).append('\n');
                }
            }
        }

        sb.append("direct_media = no\n");
        sb.append("from_user = ").append(trunk.sipUsername()).append('\n');
        sb.append("from_domain = ").append(trunk.host()).append('\n');
        sb.append("outbound_auth = ").append(authId).append('\n');
        sb.append("aors = ").append(aorId).append('\n');
        sb.append("rtp_symmetric = yes\n");
        sb.append("force_rport = yes\n");
        sb.append("rewrite_contact = yes\n\n");

        sb.append('[').append(aorId).append("]\n");
        sb.append("type = aor\n");
        sb.append("contact = sip:").append(hostPort).append('\n');
        sb.append("qualify_frequency = 30\n");
        sb.append("qualify_timeout = 5.0\n\n");
    }
}
