package uz.murodjon.uysotvoice.siptrunk.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import uz.murodjon.uysotvoice.agent.ami.AmiClient;
import uz.murodjon.uysotvoice.shared.util.SecretCipher;
import uz.murodjon.uysotvoice.siptrunk.config.PjsipConfigProperties;
import uz.murodjon.uysotvoice.siptrunk.entity.SipTrunkEntity;
import uz.murodjon.uysotvoice.siptrunk.repository.SipTrunkRepository;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Renders one PJSIP {@code auth}/{@code registration}/{@code endpoint}/{@code aor}
 * block per managed {@code sip_trunk} row into a file Asterisk's {@code pjsip.conf} is
 * expected to {@code #include} (report #7), then asks {@link AmiClient} to reload
 * {@code res_pjsip.so} so it takes effect immediately.
 *
 * <p>Regenerates the <strong>whole</strong> file from the current DB state on every
 * call rather than patching individual sections — simpler and safer than incremental
 * diffing, and cheap enough for how rarely trunks change (an admin action, not a hot
 * path). Reuses the transport/context (`transport-trunk`/`from-trunk`) already defined
 * in the hand-written {@code pjsip.conf} — a managed trunk does not need its own.
 */
@Service
public class PjsipConfigWriter {

    private static final Logger log = LoggerFactory.getLogger(PjsipConfigWriter.class);
    private static final String HEADER = """
            ; Generated by PjsipConfigWriter (report #7) — DO NOT EDIT BY HAND.
            ; Rewritten from scratch every time a managed sip_trunk row changes; any
            ; manual edit here is lost on the next trunk create/update/delete.
            ; #include this file from pjsip.conf's [global] section (or anywhere top-level).

            """;

    private final SipTrunkRepository repo;
    private final SecretCipher cipher;
    private final PjsipConfigProperties props;
    private final AmiClient ami;

    public PjsipConfigWriter(SipTrunkRepository repo, SecretCipher cipher, PjsipConfigProperties props,
                              AmiClient ami) {
        this.repo = repo;
        this.cipher = cipher;
        this.props = props;
        this.ami = ami;
    }

    /**
     * Called after any create/update/delete/enable-disable of a managed trunk.
     * Best-effort: logs and returns on failure rather than throwing — the {@code
     * sip_trunk} row is already saved and is the source of truth; this is only
     * keeping Asterisk's live config in sync with it, which can be retried later
     * (the next change to any trunk regenerates the whole file again).
     */
    public void regenerateAndReload() {
        if (!props.enabled()) {
            return;
        }
        if (props.configDir() == null || props.configDir().isBlank()) {
            log.warn("voice-agent.siptrunk.config-dir is not set — cannot write generated PJSIP config");
            return;
        }
        List<SipTrunkEntity> trunks = repo.findAllManagedEnabledEntities();
        Path file = Path.of(props.configDir(), props.configFileName());
        try {
            Files.writeString(file, render(trunks), StandardCharsets.UTF_8);
        } catch (IOException e) {
            log.warn("Could not write {}: {}", file, e.getMessage());
            return;
        }
        boolean reloaded = ami.reloadPjsip();
        log.info("Regenerated {} ({} managed trunk(s)) — Asterisk reload {}",
                file, trunks.size(), reloaded ? "ok" : "skipped/failed, will retry on next change");
    }

    private String render(List<SipTrunkEntity> trunks) {
        StringBuilder sb = new StringBuilder(HEADER);
        for (SipTrunkEntity trunk : trunks) {
            appendTrunk(sb, trunk);
        }
        return sb.toString();
    }

    private void appendTrunk(StringBuilder sb, SipTrunkEntity trunk) {
        String password;
        try {
            password = cipher.decrypt(trunk.getSipPasswordEnc());
        } catch (Exception e) {
            log.warn("Skipping trunk {} in generated PJSIP config — password could not be decrypted: {}",
                    trunk.getId(), e.getMessage());
            return;
        }
        String endpoint = trunk.getPjsipEndpoint();
        String authId = endpoint + "-auth";
        String aorId = endpoint + "-aor";
        String hostPort = trunk.getHost() + ":" + trunk.getPort();

        sb.append("; --- sip_trunk.id=").append(trunk.getId())
                .append(" (company_id=").append(trunk.getCompanyId()).append(") ---\n");

        sb.append('[').append(authId).append("]\n");
        sb.append("type = auth\n");
        sb.append("auth_type = userpass\n");
        sb.append("username = ").append(trunk.getSipUsername()).append('\n');
        sb.append("password = ").append(password).append("\n\n");

        sb.append('[').append(endpoint).append("-reg]\n");
        sb.append("type = registration\n");
        sb.append("transport = transport-trunk\n");
        sb.append("outbound_auth = ").append(authId).append('\n');
        sb.append("server_uri = sip:").append(hostPort).append('\n');
        sb.append("client_uri = sip:").append(trunk.getSipUsername()).append('@').append(hostPort).append('\n');
        sb.append("retry_interval = 60\n");
        sb.append("expiration = 120\n\n");

        sb.append('[').append(endpoint).append("]\n");
        sb.append("type = endpoint\n");
        sb.append("transport = transport-trunk\n");
        sb.append("context = from-trunk\n");
        sb.append("disallow = all\n");
        sb.append("allow = ulaw\n");
        sb.append("allow = alaw\n");
        sb.append("direct_media = no\n");
        sb.append("from_user = ").append(trunk.getSipUsername()).append('\n');
        sb.append("from_domain = ").append(trunk.getHost()).append('\n');
        sb.append("outbound_auth = ").append(authId).append('\n');
        sb.append("aors = ").append(aorId).append('\n');
        sb.append("rtp_symmetric = yes\n");
        sb.append("force_rport = yes\n");
        sb.append("rewrite_contact = yes\n\n");

        sb.append('[').append(aorId).append("]\n");
        sb.append("type = aor\n");
        sb.append("contact = sip:").append(hostPort).append('\n');
        sb.append("qualify_frequency = 30\n");
        sb.append("qualify_timeout = 5.0\n\n");
    }
}
