package uz.murodjon.robotcallv2.shared.exception;

/**
 * Every message the API can return, paired with its code in one place — a frontend
 * translates by {@link #name()} (sent as {@code ResponseData.messageCode}), so a message's
 * wording is free to change here without ever breaking that mapping, and a code can never
 * exist without a message or vice versa.
 */
public enum ErrorCode {

    // not found
    CAMPAIGN_NOT_FOUND("Campaign %s not found"),
    TARGET_NOT_FOUND("Target %s not found"),
    COMPANY_NOT_FOUND("Company %s not found"),
    COMPANY_CONFIG_NOT_FOUND("Company config %s not found"),
    CONTACT_NOT_FOUND("Contact %s not found"),
    CLIENT_MEMORY_NOT_FOUND("No memory for client %s yet"),
    CRM_INTEGRATION_NOT_FOUND("CRM integration %s not found"),
    INBOUND_ROUTE_NOT_FOUND("Inbound route %s not found"),
    REPORT_SCHEDULE_NOT_FOUND("Report schedule %s not found"),
    SCENARIO_NOT_FOUND("Scenario %s not found"),
    SIP_TRUNK_NOT_FOUND("SIP trunk %s not found"),
    FILE_NOT_FOUND("File %s not found"),
    USER_NOT_FOUND("User %s not found"),
    ROLE_NOT_FOUND("Role %s not found"),
    CALL_NOT_FOUND("Call %s not found"),
    INVOICE_NOT_FOUND("Invoice %s not found"),
    DO_NOT_CALL_ENTRY_NOT_FOUND("No active do-not-call entry for %s"),
    OPERATOR_SNAPSHOT_NOT_FOUND("No operator snapshot for channel %s"),
    CALL_RECORDING_NOT_FOUND("No recording for call %s"),
    TTS_VOICE_NOT_FOUND("TTS voice %s not found"),
    KNOWLEDGE_ITEM_NOT_FOUND("Knowledge base item %s not found"),
    AI_AGENT_NOT_FOUND("AI agent %s not found"),
    AGENT_WIDGET_NOT_FOUND("Agent widget %s not found"),
    KNOWLEDGE_SOURCE_NOT_FOUND("Knowledge source %s not found"),
    TOOL_NOT_FOUND("Tool %s not found"),
    API_KEY_NOT_FOUND("API key %s not found"),
    CONVERSION_GOAL_NOT_FOUND("Conversion goal %s not found"),
    MCP_CONNECTION_NOT_FOUND("MCP connection %s not found"),
    SECRET_NOT_FOUND("Secret %s not found"),
    TARGET_SOURCE_NOT_FOUND("Campaign %s has no target source configured"),
    CAMPAIGN_VARIANT_NOT_FOUND("Campaign variant %s not found"),

    // forbidden
    NO_USER_SESSION("no user session on this request"),
    CROSS_COMPANY_ACCESS_FORBIDDEN("cross-company access forbidden"),
    ROLE_NOT_ASSIGNABLE("role %s can only be assigned by platform staff"),
    PERMISSION_DENIED("your role does not include this action"),
    ACCOUNT_BLOCKED("this account has been blocked"),
    ACCOUNT_NOT_ACTIVATED("account not activated yet — use the invite link first"),
    ACCOUNT_INACTIVE("this account is no longer active"),
    REFRESH_TOKEN_INVALID("invalid or already used refresh token"),
    REFRESH_TOKEN_EXPIRED("refresh token has expired — log in again"),
    SCENARIO_BUILTIN_READONLY("Built-in scenario '%s' cannot be edited — clone it first"),
    AGENT_WIDGET_ORIGIN_FORBIDDEN("Origin %s is not allowed for this widget"),

    // validation
    LOGIN_INVALID_CREDENTIALS("username yoki parol noto'g'ri"),
    ACTIVATION_TOKEN_INVALID("invalid or already used activation token"),
    ACTIVATION_TOKEN_EXPIRED("activation token has expired — ask an admin to invite you again"),
    RESET_TOKEN_INVALID("invalid or already used reset token"),
    RESET_TOKEN_EXPIRED("reset token has expired — request a new one"),
    SCENARIO_DEFINITION_INVALID("Invalid scenario definition: %s"),
    WEB_TEST_SOURCE_INVALID("give at most one of campaignId, scenarioId or definition; targetId needs campaignId"),
    CAMPAIGN_DIAL_WINDOW_INVALID("dialWindowStart must be before dialWindowEnd"),
    CAMPAIGN_DIAL_WINDOW_OUT_OF_RANGE(
            "Campaign dial window (%s-%s) must fit inside the company's allowed dial window (%s-%s)"),
    CAMPAIGN_RECURRENCE_INVALID("Invalid campaign recurrence configuration: %s"),
    TTS_VOICE_UNKNOWN("Unknown TTS voice '%s'; available: %s"),
    TTS_VOICE_LANGUAGE_MISMATCH("TTS voice '%s' speaks %s, so it cannot be the voice for %s"),
    AI_MODEL_UNKNOWN("Unknown AI model '%s'; available: %s"),
    STT_MODEL_UNKNOWN("Unknown STT model '%s'; available: %s"),
    TTS_MODEL_UNKNOWN("Unknown TTS model '%s'; available: %s"),
    STT_MODEL_PROVIDER_MISMATCH("STT model '%s' belongs to provider '%s' — set sttProvider to it"),
    TTS_MODEL_PROVIDER_MISMATCH("TTS model '%s' belongs to provider '%s' — set ttsProvider to it"),
    REALTIME_MODEL_PROVIDER_MISMATCH("Realtime model '%s' belongs to engine '%s' — set realtimeProvider to it"),
    ENGINE_STT_PROVIDER_UNKNOWN("Unknown STT provider '%s'; available: %s"),
    ENGINE_TTS_PROVIDER_UNKNOWN("Unknown TTS provider '%s'; available: %s"),
    ENGINE_REALTIME_NOT_AVAILABLE("REALTIME mode has no engine wired in this build — use CASCADE"),
    ENGINE_REALTIME_PROVIDER_UNKNOWN("Unknown realtime engine '%s'; available: %s"),
    ENGINE_REALTIME_PROVIDER_REQUIRED("realtimeProvider is required — no default is configured; pick one of %s"),
    CSV_EMPTY("CSV is empty"),
    CSV_PHONE_COLUMN_MISSING("CSV needs a 'phone' column; found: %s"),
    CSV_PHONE_EMPTY("phone is empty"),
    CSV_NAME_EMPTY("name is empty"),
    CSV_CLIENT_ID_NOT_NUMBER("clientId '%s' is not a number"),
    COMPANY_CONFIG_DEFAULT_LANGUAGE_NOT_IN_SUPPORTED("defaultLanguage '%s' must be one of supportedLanguages %s"),
    LANGUAGE_CODE_INVALID("Unknown language '%s'; supported: %s"),
    COMPANY_CONFIG_LANGUAGE_NOT_SUPPORTED("Language '%s' is not supported by this company; supported: %s"),
    COMPANY_CONFIG_DISCLOSURE_INCOMPLETE(
            "disclosureText qo'ng'iroq avtomatik ekanini va yozib olinayotganini aytishi shart (§11.1); "
                    + "platforma matni ishlatilishi uchun bo'sh qoldiring"),
    EMAIL_ALREADY_TAKEN("bu email allaqachon band"),
    CURRENT_PASSWORD_INCORRECT("joriy parol noto'g'ri"),
    SCHEDULE_START_AFTER_END("boshlanish vaqti tugash vaqtidan oldin bo'lishi kerak"),
    PROFILE_TABLE_CONFIG_KEY_BLANK("config key bo'sh bo'lishi mumkin emas"),
    PROFILE_TABLE_CONFIG_KEY_TOO_LONG("config key 100 belgidan oshmasligi kerak"),
    ROLE_PERMISSIONS_EMPTY("a role needs at least one permission"),
    ROLE_PERMISSION_NOT_GRANTABLE("permission %s cannot be granted to a company role"),
    SEARCH_QUERY_BLANK("q: must not be blank"),
    REPORT_BULK_ACTION_UNKNOWN("Unknown bulk action '%s'"),
    REPORT_SCHEDULE_FORMAT_INVALID("format must be one of %s, got '%s'"),
    REPORT_EXPORT_FORMAT_UNKNOWN("Unknown export format '%s' — use csv, pdf, or xlsx"),
    SCENARIO_KEY_DERIVE_FAILED("Could not derive a scenario key from name '%s'"),
    KNOWLEDGE_KEY_BLANK("knowledge key cannot be empty"),
    KNOWLEDGE_ANSWER_BLANK("the Uzbek answer cannot be empty"),
    CRM_INTEGRATION_APP_NOT_CONFIGURED("Save appName/grants first"),
    OAUTH_STATE_INVALID("invalid state"),
    DATE_RANGE_INVALID("'from' must be before 'to'"),
    DATE_RANGE_TOO_LONG("range must not exceed %s days"),
    INSTANT_PARSE_FAILED("'%s' is not an ISO-8601 instant"),
    IMAGE_UPLOAD_FILE_MISSING("no file uploaded"),
    IMAGE_UPLOAD_TOO_LARGE("image must be at most 5 MB"),
    IMAGE_UPLOAD_TYPE_UNSUPPORTED("unsupported image type '%s'; allowed: %s"),
    IMAGE_UPLOAD_READ_FAILED("could not read uploaded file: %s"),
    AUDIO_UPLOAD_FILE_MISSING("no audio file uploaded"),
    AUDIO_UPLOAD_INVALID("could not decode audio: %s"),
    AUDIO_UPLOAD_TOO_LONG("audio is longer than %s seconds"),
    PHONE_INVALID("Invalid phone number: '%s' (expected 3-15 digits, optional leading '+')"),
    SIP_TRUNK_PASSWORD_REQUIRED("sipPassword is required for a managed trunk"),
    SIP_TRUNK_PASSWORD_REQUIRED_ON_SWITCH("sipPassword is required when switching a trunk to managed mode"),
    SIP_TRUNK_MODE_CONFLICT(
            "provide either pjsipEndpoint (manual mode) or host/sipUsername/sipPassword (managed mode), not both"),
    SIP_TRUNK_MODE_MISSING(
            "either pjsipEndpoint (manual mode) or host+sipUsername+sipPassword (managed mode) is required"),
    SIP_TRUNK_USERNAME_REQUIRED("sipUsername is required for a managed trunk"),
    SIP_TRUNK_TRANSPORT_UNSUPPORTED("transport '%s' is not wired to an Asterisk transport yet — only UDP is supported"),
    PLAYBACK_FILE_BLANK("file must not be blank"),
    PLAYBACK_FILE_OUTSIDE_BASE("file must be inside %s"),
    PLAYBACK_FILE_NOT_FOUND("No such playback file: %s"),
    SAY_TEXT_BLANK("text must not be blank"),
    SAY_TEXT_TOO_LONG("text is longer than %s characters"),
    VOICE_SPEED_OUT_OF_RANGE("speed must be between 0.25 and 4.0, got %s"),
    AI_AGENT_TEMPERATURE_OUT_OF_RANGE("temperature must be between 0 and 2, got %s"),
    AI_AGENT_MAX_OUTPUT_TOKENS_OUT_OF_RANGE("maxOutputTokens must be between 1 and 4096, got %s"),
    TARGET_SOURCE_URL_INVALID("target source url must be an http(s) address, got '%s'"),
    TARGET_SOURCE_RESPONSE_INVALID("target source did not answer with a JSON array of rows: %s"),
    TARGET_SOURCE_STEPS_REQUIRED("a chained target source needs at least one step"),
    TARGET_SOURCE_STEP_INVALID("target source step %s is not usable: %s"),
    ZERO_PII_STORE_AUDIO_CONFLICT("Call audio cannot be stored when zero-PII retention is enabled"),
    TOOL_URL_INVALID("tool url must be a public http(s) address, got '%s'"),
    API_KEY_SCOPES_REQUIRED("an API key must be granted at least one scope"),
    CONVERSION_GOAL_UNKNOWN("no conversion goal '%s' is configured for this company"),
    MCP_URL_INVALID("MCP server url must be a public https address (connection '%s')"),
    API_KEY_EXPIRY_IN_PAST("expiresAt must be in the future, got %s"),
    WEBHOOK_URL_INVALID("webhook url must be a public http(s) address, got '%s'"),
    KNOWLEDGE_SOURCE_URL_REQUIRED("URL is required for a URL knowledge source"),
    KNOWLEDGE_SOURCE_URL_INVALID("knowledge source url must be an http(s) address, got '%s'"),
    KNOWLEDGE_SOURCE_FILE_REQUIRED("storedFileId is required for a %s knowledge source"),

    // conflict
    CONTACT_PHONE_EXISTS("Contact with phone %s already exists"),
    TTS_PROVIDER_UNAVAILABLE("No TTS provider available for language %s"),
    TTS_VOICE_PROVIDER_UNAVAILABLE("Voice '%s' is spoken by %s, which is not a TTS provider enabled in this build"),
    STT_PROVIDER_UNAVAILABLE("No STT provider is enabled in this build"),
    INBOUND_ROUTE_DID_EXISTS("An enabled inbound route for %s already exists"),
    USER_EMAIL_TAKEN("email %s already registered"),
    USER_USERNAME_TAKEN("username %s already registered"),
    LAST_ADMIN_ROLE_CHANGE_FORBIDDEN("cannot change the role of the last admin — promote another user first"),
    SELF_ACTION_FORBIDDEN("cannot %s your own account"),
    LAST_ADMIN_ACTION_FORBIDDEN("cannot %s the last admin"),
    ROLE_NAME_TAKEN("a role named %s already exists in this company"),
    ROLE_LIMIT_EXCEEDED("a company cannot have more than %s roles of its own"),
    ROLE_SYSTEM_READONLY("system role %s cannot be edited or deleted"),
    ROLE_IN_USE("role %s is still assigned to %s user(s)"),
    SCENARIO_KEY_EXISTS("Scenario key '%s' already exists"),
    AI_AGENT_IN_USE("AI agent %s is still used by %s campaign(s) and %s inbound route(s)"),
    TOOL_IN_USE("Tool %s is still used by %s AI agent(s)"),
    AGENT_WIDGET_DISABLED("Agent widget %s is currently disabled"),
    AGENT_WIDGET_DAILY_LIMIT_REACHED("This widget has reached its agent's daily call limit (%s)"),
    AGENT_WIDGET_BUSY("All of this agent's lines are busy (%s concurrent calls); try again shortly"),
    SECRET_KEY_EXISTS("Secret with key '%s' already exists in this company"),
    MCP_CONNECTION_NAME_EXISTS("An MCP connection named '%s' already exists in this company"),
    AI_AGENT_DISABLED("AI agent %s is disabled — enable it before starting the campaign"),
    TARGET_SOURCE_DISABLED("Campaign %s has its target source disabled — enable it before syncing"),
    SIP_TRUNK_DEFAULT_DELETE_FORBIDDEN("Cannot delete the default trunk — set another one as default first"),
    SIP_TRUNK_SELECTION_UNAVAILABLE("None of the selected SIP trunks %s is enabled"),
    CALL_NOT_ACTIVE("No active call for channel %s"),
    WEB_TEST_NOT_CONFIGURED("Browser test calls are not configured (voice-agent.asterisk.web-test.ws-url is blank)"),
    TTS_DISABLED("TTS is disabled (voice-agent.tts.enabled=false)"),

    // external service
    TOOL_EXECUTION_FAILED("Tool %s execution failed: %s"),
    MCP_REQUEST_FAILED("MCP server '%s' failed: %s"),
    MCP_AUTH_REQUIRED("MCP server '%s' refused the credential"),
    MCP_RESPONSE_INVALID("MCP server '%s' answered with something unusable: %s"),
    TARGET_SOURCE_FETCH_FAILED("target source %s failed: %s"),
    ARI_ORIGINATE_FAILED("Originate to %s via %s failed: %s"),
    ARI_PLAYBACK_FAILED("Failed to play %s: %s"),
    ARI_NOT_CONNECTED("ARI is not connected"),
    ARI_DTMF_FAILED("Failed to send DTMF '%s' on channel %s"),
    STT_GOOGLE_CLIENT_UNAVAILABLE("client is not available"),
    STT_GEMINI_CONNECT_FAILED("gemini stt connection failed: %s"),
    STT_GEMINI_CLIENT_UNAVAILABLE("gemini stt client is not available (check GEMINI_API_KEY)"),
    STT_YANDEX_CHANNEL_UNAVAILABLE("channel is not available (check STT_YANDEX_API_KEY)"),
    STT_DEEPGRAM_CONNECT_FAILED("deepgram connection failed: %s"),
    STT_DEEPGRAM_STREAM_FAILED("deepgram stream failed: %s"),
    STT_PREVIEW_INTERRUPTED("recognition was interrupted before the transcript arrived"),
    AUDIO_TRANSCODER_UNAVAILABLE("ffmpeg could not be started from '%s' — install it or set voice-agent.audio.ffmpeg-path"),
    AUDIO_TRANSCODER_FAILED("ffmpeg failed: %s"),
    TTS_GOOGLE_CLIENT_UNAVAILABLE("client is not available"),
    TTS_GOOGLE_AUDIO_PARSE_FAILED("failed to parse audio: %s"),
    TTS_GEMINI_CONNECT_FAILED("gemini tts connection failed: %s"),
    TTS_GEMINI_SYNTH_FAILED("gemini tts synthesis failed: %s"),
    TTS_GEMINI_CLIENT_UNAVAILABLE("gemini tts client is not available (check GEMINI_API_KEY)"),
    TTS_YANDEX_CHANNEL_UNAVAILABLE("channel is not available (check TTS_YANDEX_API_KEY)"),
    TTS_YANDEX_STREAM_ERROR("stream failed: %s"),
    STT_AISHA_CONNECT_FAILED("realtime connection failed: %s"),
    TTS_AISHA_CONNECT_FAILED("realtime connection failed: %s"),
    TTS_AISHA_SYNTH_FAILED("synthesis failed: %s"),
    TTS_AISHA_AUDIO_PARSE_FAILED("failed to parse audio: %s"),
    TTS_OPENAI_CLIENT_UNAVAILABLE("openai tts client is not available (check OPENAI_API_KEY)"),
    TTS_OPENAI_SYNTH_FAILED("openai tts synthesis failed: %s"),
    STT_OPENAI_CLIENT_UNAVAILABLE("openai stt client is not available (check OPENAI_API_KEY)"),
    STT_OPENAI_CONNECT_FAILED("openai stt connection failed: %s"),
    REALTIME_GEMINI_CONNECT_FAILED("realtime connection failed: %s"),
    REALTIME_GEMINI_SETUP_FAILED("session setup was not acknowledged within %ss"),
    UYSOT_OAUTH_LOGIN_NOT_AVAILABLE("not configured yet (ROADMAP Bosqich D)"),
    UYSOT_OAUTH_NOT_CONFIGURED("Uysot OAuth endpoints are not configured yet"),
    UYSOT_OAUTH_TOKEN_EXCHANGE_HTTP_ERROR("token exchange HTTP %s"),
    UYSOT_OAUTH_TOKEN_EXCHANGE_FAILED("token exchange failed: %s"),
    UYSOT_OAUTH_TOKEN_MISSING("token response had no access_token"),
    ENCRYPTION_KEY_NOT_SET("voice-agent.encryption.secret-key is not set"),
    REPORT_PDF_RENDER_FAILED("Failed to render report PDF: %s"),
    REPORT_XLSX_RENDER_FAILED("Failed to render report XLSX: %s"),
    INVOICE_PDF_RENDER_FAILED("Failed to render invoice PDF: %s"),
    JWT_KEY_NOT_SET("voice-agent.security.jwt.secret is not set"),
    IMAGE_UPLOAD_STORAGE_UNAVAILABLE("image upload failed — storage unavailable"),
    FILE_READ_FAILED("could not read file %s"),
    KNOWLEDGE_SOURCE_UNREADABLE("could not read the %s document: %s"),
    KNOWLEDGE_SOURCE_FETCH_FAILED("could not fetch %s: %s"),
    KNOWLEDGE_SOURCE_EMPTY("the document carries no readable text — a scanned PDF has no text layer"),

    // framework-level (ApiExceptionHandler) — not an AppException, but the same envelope
    VALIDATION_FAILED("Validation failed"),
    MALFORMED_REQUEST_BODY("Malformed or invalid request body"),
    MISSING_REQUIRED_PARAMETER("Missing required parameter: %s"),
    INVALID_PARAMETER_VALUE("Invalid value for parameter: %s"),
    NO_SUCH_ENDPOINT("No such endpoint: %s"),
    METHOD_NOT_ALLOWED("Request method '%s' is not supported"),
    INTERNAL_SERVER_ERROR("Internal server error");

    private final String template;

    ErrorCode(String template) {
        this.template = template;
    }

    /** Interpolates {@code args} into this code's template with {@link String#format}. */
    public String format(Object... args) {
        return args.length == 0 ? template : String.format(template, args);
    }
}
