package uz.murodjon.robotcallv2.aiagent.application.dto;

import uz.murodjon.robotcallv2.aiagent.domain.entity.*;
import uz.murodjon.robotcallv2.aiagent.domain.enums.*;
import uz.murodjon.robotcallv2.scenario.domain.entity.ScenarioDefinition;
import uz.murodjon.robotcallv2.shared.dialog.AgentPersona;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * {@link AiAgent} representation returned to the agent screens.
 */
public record AiAgentRow(
        long id,
        long companyId,
        String name,
        String description,
        Long scenarioId,
        String scenarioName,
        AgentTemplate templateId,
        String firstMessage,
        String systemPrompt,
        ScenarioMode scenarioMode,
        ScenarioDefinition scenarioDefinition,
        boolean preemptiveGeneration,
        boolean ivrNavigationEnabled,
        boolean useRag,
        String language,
        PipelineMode pipelineMode,
        String realtimeProvider,
        String pipecatStt,
        String pipecatLlm,
        String pipecatTts,
        String sttProvider,
        String sttModel,
        String ttsProvider,
        String ttsModel,
        String ttsVoice,
        Double voiceSpeed,
        Double voiceStability,
        Double voiceSimilarityBoost,
        Map<String, String> languageVoices,
        AgentPersona persona,
        boolean disclosureEnabled,
        String llmModel,
        String fastLlmModel,
        Double temperature,
        Integer maxOutputTokens,
        List<DataExtractionField> dataNeeded,
        List<DataEvaluationCriterion> dataEvaluation,
        boolean zeroPiiRetention,
        boolean storeCallAudio,
        Integer conversationRetentionDays,
        Integer maxConversationDurationSeconds,
        Integer silenceEndCallTimeoutSeconds,
        Integer turnTimeoutSeconds,
        Integer concurrentCallsLimit,
        Integer dailyCallsLimit,
        AgentWebhookConfig initiationWebhook,
        AgentWebhookConfig postCallWebhook,
        AmbientSound ambientSound,
        Double ambientSoundVolume,
        Double ambientSoundFadeInSeconds,
        AmbientSound thinkingSound,
        Double thinkingSoundVolume,
        boolean noiseCancellationEnabled,
        NoiseCancellationMode noiseCancellationMode,
        boolean emotionAdaptiveVoice,
        boolean dtmfInputEnabled,
        VoicemailAction voicemailAction,
        String voicemailMessage,
        boolean midCallSmsEnabled,
        String midCallSmsTemplate,
        String transferPhoneNumber,
        String transferMessage,
        InterruptionSensitivity interruptionSensitivity,
        Integer endpointingDelayMs,
        List<PronunciationRule> pronunciationRules,
        List<PostCallAction> postCallActions,
        Set<Long> sipTrunkIds,
        boolean enabled,
        Instant createdAt,
        Long createdBy,
        String createdByName
) {

    public static AiAgentRow of(AiAgent agent, String scenarioName, String createdByName) {
        return new AiAgentRow(
                agent.id(),
                agent.companyId(),
                agent.name(),
                agent.description(),
                agent.script().scenarioId(),
                scenarioName,
                agent.script().templateId(),
                agent.script().firstMessage(),
                agent.script().systemPrompt(),
                agent.script().mode(),
                agent.script().definition(),
                agent.preemptiveGeneration(),
                agent.ivrNavigationEnabled(),
                agent.useRag(),
                agent.language(),
                agent.speechEngine().mode(),
                agent.speechEngine().realtimeProvider(),
                agent.speechEngine().pipecatStt(),
                agent.speechEngine().pipecatLlm(),
                agent.speechEngine().pipecatTts(),
                agent.speechEngine().sttProvider(),
                agent.speechEngine().sttModel(),
                agent.speechEngine().ttsProvider(),
                agent.speechEngine().ttsModel(),
                agent.voice().defaultVoice(),
                agent.voice().speed(),
                agent.voice().stability(),
                agent.voice().similarityBoost(),
                agent.voice().perLanguage(),
                agent.persona(),
                agent.disclosureEnabled(),
                agent.llmModel(),
                agent.fastLlmModel(),
                agent.temperature(),
                agent.maxOutputTokens(),
                agent.dataNeeded(),
                agent.dataEvaluation(),
                agent.dataPolicy().zeroPiiRetention(),
                agent.dataPolicy().storeCallAudio(),
                agent.dataPolicy().conversationRetentionDays(),
                agent.limits().maxConversationDurationSeconds(),
                agent.limits().silenceEndCallTimeoutSeconds(),
                agent.limits().turnTimeoutSeconds(),
                agent.limits().concurrentCallsLimit(),
                agent.limits().dailyCallsLimit(),
                agent.initiationWebhook(),
                agent.postCallWebhook(),
                agent.ambience().background(),
                agent.ambience().backgroundVolume(),
                agent.ambience().backgroundFadeInSeconds(),
                agent.ambience().thinking(),
                agent.ambience().thinkingVolume(),
                agent.ambience().noiseCancellationEnabled(),
                agent.ambience().noiseCancellationMode(),
                agent.voice().emotionAdaptive(),
                agent.callBehaviour().dtmfInputEnabled(),
                agent.callBehaviour().voicemailAction(),
                agent.callBehaviour().voicemailMessage(),
                agent.callBehaviour().midCallSmsEnabled(),
                agent.callBehaviour().midCallSmsTemplate(),
                agent.callBehaviour().transferPhoneNumber(),
                agent.callBehaviour().transferMessage(),
                agent.callBehaviour().interruptionSensitivity(),
                agent.callBehaviour().endpointingDelayMs(),
                agent.pronunciationRules(),
                agent.postCallActions(),
                agent.sipTrunkIds(),
                agent.enabled(),
                agent.createdAt(),
                agent.createdBy(),
                createdByName
        );
    }
}
