package uz.murodjon.uysotvoice.agent.dialog;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.math.BigDecimal;

/**
 * Dialog engine settings. Bound from {@code voice-agent.dialog.*} (PROJECT.md §4, §12).
 *
 * @param enabled        master switch for the LLM dialog engine
 * @param autoStart      when true, the bot greets and drives the conversation as soon
 *                       as media is up (Stage 7 verification without a DB/campaign)
 * @param language       BCP-47 conversation language (also used to route STT/TTS)
 * @param maxTurns       hard cap on conversation turns before auto-closing (§4.4)
 * @param maxCallSeconds hard cap on call duration in seconds before auto-closing (§4.4)
 * @param testContext    static client facts injected into the prompt for verification
 */
@ConfigurationProperties(prefix = "voice-agent.dialog")
public record DialogProperties(
        boolean enabled,
        boolean autoStart,
        String language,
        int maxTurns,
        int maxCallSeconds,
        TestContext testContext
) {

    /**
     * Placeholder client context used until the campaign/target lifecycle (Stage 10)
     * supplies real facts. Facts are FACT — never generated by the LLM (§4.4).
     *
     * @param clientName     debtor's name for identity check
     * @param debtAmount     outstanding amount (stated verbatim, never changed)
     * @param currency       currency label spoken alongside the amount
     * @param dueDate        original due date, ISO {@code yyyy-MM-dd} (blank to omit)
     * @param contractNumber contract reference
     * @param goal           campaign goal appended to the system prompt
     */
    public record TestContext(
            String clientName,
            BigDecimal debtAmount,
            String currency,
            String dueDate,
            String contractNumber,
            String goal
    ) {
    }
}
