package uz.murodjon.robotcallv2.agent.dialog;

import java.math.BigDecimal;

/**
 * Placeholder client context used until the campaign/target lifecycle (Stage 10)
 * supplies real facts. Facts are FACT — never generated by the LLM (§4.4).
 *
 * @param clientName     debtor's name for identity check
 * @param debtAmount     outstanding amount (stated verbatim, never changed)
 * @param currency       currency label spoken alongside the amount
 * @param dueDate        original due date, ISO {@code yyyy-MM-dd} (blank to omit)
 * @param contractNumber contract reference
 * @param goal           campaign goal appended to the system prompt
 * @param scenarioKey    scenario a manual/inbound test call without a {@code scenarioId}
 *                       runs (ROADMAP A.3); defaults to {@code debt-collection} so
 *                       today's manual-call behavior is unchanged when nothing is chosen
 */
public record TestContextProperties(
        String clientName,
        BigDecimal debtAmount,
        String currency,
        String dueDate,
        String contractNumber,
        String goal,
        String scenarioKey
) {

    public TestContextProperties {
        if (scenarioKey == null || scenarioKey.isBlank()) {
            scenarioKey = "debt-collection";
        }
    }
}
